language: objective-c
osx_image: xcode11
env:
  matrix:
    - SCHEME=MQTTClientiOS DESTINATION='platform=iOS Simulator,name=iPhone 8,OS=12.1'
    - SCHEME=MQTTClientiOS DESTINATION='platform=iOS Simulator,name=iPhone 7,OS=13.0'
    - SCHEME=MQTTClientmacOS DESTINATION='platform=macOS'
before_install:
  - gem install xcpretty
  - brew install mosquitto
before_script: 
  - ./brokers/mosquitto/start.sh
script: 
  - xcodebuild clean test -workspace MQTTClient/MQTTClient.xcworkspace -scheme $SCHEME -destination "$DESTINATION";
after_script: 
  - ./brokers/mosquitto/stop.sh
after_success:
    - if [ "$SCHEME" == "MQTTClientmacOS" ]; then
        bash <(curl -s https://codecov.io/bash);
      fi
